[env:uno]
platform = atmelavr
board = uno
framework = arduino

; Use the bundled or local FreeRTOS library, don't modify Arduino_FreeRTOS_Library directory
lib_extra_dirs = Arduino_FreeRTOS_Library

build_flags =
  -D LED_BUILTIN=13

monitor_speed = 9600

; If a local copy of Arduino_FreeRTOS_Library is not present, fetch it from GitHub
lib_deps = https://github.com/feilipu/Arduino_FreeRTOS_Library

